version: '2'
services:
    kilocms-app:
        image: kilocms
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://kilocms-mysql:3306/kilocms?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=kilocms-elasticsearch:9300
        ports:
            - 8080:8080
    kilocms-mysql:
        extends:
            file: mysql.yml
            service: kilocms-mysql
    kilocms-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: kilocms-elasticsearch
